<?php
$peliculas = [
    [
        'nom' => 'El silencio de los corderos',
        'imatge' => 'https://static.filmin.es/images/es/media/26512/1/still_0_3_1920x1080.webp',
        'horaris_projeccio' => [
            '19:00',
            '21:30',
            '23:00',
        ],
        'sinopsi' => 'Una joven agente del FBI busca la ayuda de un prisionero, el Dr. Hannibal Lecter, un brillante psiquiatra y asesino en serie, para atrapar a otro asesino que ha secuestrado a una joven.',
        'durada' => '118 min',
        'director' => 'Jonathan Demme',
        'repartiment' => 'Jodie Foster, Anthony Hopkins, Scott Glenn',
        'qualificacio' => '+18',
        'genere' => 'Thriller, Terror, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/6iB21hsprAQ?si=1qm79vybDR55QVAS',
    ],
    [
        'nom' => 'Pulp Fiction',
        'imatge' => 'https://imagenes.elpais.com/resizer/v2/UU7EK3LSSRL77HQH5ZHQRJAJIA.jpg?auth=55427cda34ee0832111eb322a50b2305b17bcf0f8986aec80f41c7208a2aeeee&width=414',
        'horaris_projeccio' => [
            '20:00',
            '22:30',
            '21:00',
        ],
        'sinopsi' => 'Varias historias entrelazadas en el mundo del crimen de Los Ángeles, incluyendo a un boxeador, un asesino y una pareja de delincuentes.',
        'durada' => '154 min',
        'director' => 'Quentin Tarantino',
        'repartiment' => 'John Travolta, Uma Thurman, Samuel L. Jackson',
        'qualificacio' => '+18',
        'genere' => 'Acció, Drama, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/tGpTpVyI_OQ?si=A4ORZDNXpKvN5V3H',
    ],
    [
        'nom' => 'La lista de Schindler',
        'imatge' => 'https://www.autopista.es/uploads/s1/99/59/52/2/uno-de-los-carteles-de-la-aclamada-pelicula-la-lista-de-schindler.jpeg',
        'horaris_projeccio' => [
            '18:30',
            '19:30',
            '20:00',
        ],
        'sinopsi' => 'Oskar Schindler, un industrial alemán, arriesga la vida i la seva fortuna per salvar a més de mil jueus durant Holocaust.',
        'durada' => '195 min',
        'director' => 'Steven Spielberg',
        'repartiment' => 'Liam Neeson, Ben Kingsley, Ralph Fiennes',
        'qualificacio' => '+16',
        'genere' => 'Drama, Història',
        'url_trailer' => 'https://www.youtube.com/embed/7q-ETFeMxwI?si=Ujmijp6XKylEPcL8',
    ],
    [
        'nom' => 'Forrest Gump',
        'imatge' => 'https://cdn.aarp.net/content/dam/aarpe/es/home/entretenimiento/cine-y-television/info-2022/forrest-gump/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/entertainment/movies-for-grownups/2022/03/1140-forrest-gump-bench-esp.jpg',
        'horaris_projeccio' => [
            '20:00',
            '18:00',
            '21:15',
        ],
        'sinopsi' => 'La vida de Forrest Gump, un home amb discapacitat mental, que accidentalment influencia esdeveniments històrics a través de les dècades.',
        'durada' => '142 min',
        'director' => 'Robert Zemeckis',
        'repartiment' => 'Tom Hanks, Robin Wright, Gary Sinise',
        'qualificacio' => '+13',
        'genere' => 'Drama, Comèdia, Romance',
        'url_trailer' => 'https://www.youtube.com/embed/Cyh1LpxnaxI?si=OWY-VDhOBNmiyoba',
    ],
    [
        'nom' => 'Matrix',
        'imatge' => 'https://estaticos-cdn.prensaiberica.es/clip/3678c50c-e36a-4ce1-a8ea-bf7e6d655093_16-9-discover-aspect-ratio_default_0.jpg',
        'horaris_projeccio' => [
            '21:00',
            '19:15',
            '22:45',
        ],
        'sinopsi' => 'Thomas Anderson, un hacker conegut com a Neo, descobreix que el món és una simulació creada per màquines, i s uneix a una rebel·lia per alliberar la humanitat.',
        'durada' => '136 min',
        'director' => 'Lana Wachowski, Lilly Wachowski',
        'repartiment' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        'qualificacio' => '+16',
        'genere' => 'Acció, Ciència-Ficció',
        'url_trailer' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
    ],
    [
        'nom' => 'Gladiator',
        'imatge' => 'https://fotografias.antena3.com/clipping/cmsimages01/2020/04/17/E8A1569F-D03B-41CE-99A1-0726EC2FF0BC/98.jpg?crop=1279,720,x0,y0&width=1900&height=1069&optimize=high&format=webply',
        'horaris_projeccio' => [
            '19:45',
            '20:15',
            '22:00',
        ],
        'sinopsi' => 'Un general romà és traït i venut com a esclau. Ara lluita per la seva vida com a gladiador i busca venjança contra qui el va traïr.',
        'durada' => '155 min',
        'director' => 'Ridley Scott',
        'repartiment' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
        'qualificacio' => '+16',
        'genere' => 'Acció, Drama, Història',
        'url_trailer' => 'https://www.youtube.com/watch?v=P5ieIbInFpg',
    ],
    [
        'nom' => 'El gran Lebowski',
        'imatge' => 'https://pics.filmaffinity.com/El_gran_Lebowski-232559190-large.jpg',
        'horaris_projeccio' => [
            '21:30',
            '18:45',
            '20:30',
        ],
        'sinopsi' => 'Un hippie conegut com "El Dudo" es veu embolicat en una confusió que li porta a una sèrie de situacions còmiques i estranyes.',
        'durada' => '117 min',
        'director' => 'Joel Coen',
        'repartiment' => 'Jeff Bridges, John Goodman, Julianne Moore',
        'qualificacio' => '+18',
        'genere' => 'Comèdia, Crimen',
        'url_trailer' => 'https://www.youtube.com/watch?v=AkA69XT7Lq0',
    ],
    [
        'nom' => 'Inception',
        'imatge' => 'https://evoluciongeek.com/wp-content/uploads/2022/01/inception-01.jpg',
        'horaris_projeccio' => [
            '22:00',
            '20:45',
            '21:30',
        ],
        'sinopsi' => 'Un lladre especialitzat en robar idees a través dels somnis es veu obligat a realitzar l impossible: implantar una idea en la ment d una altra persona.',
        'durada' => '148 min',
        'director' => 'Christopher Nolan',
        'repartiment' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
        'qualificacio' => '+13',
        'genere' => 'Acció, Ciència-Ficció, Thriller',
        'url_trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    ],
    [
        'nom' => 'El padrino',
        'imatge' => 'https://fotos.perfil.com/2021/03/14/trim/987/555/el-padrino-1144490.jpg',
        'horaris_projeccio' => [
            '18:00',
            '20:30',
            '22:00',
        ],
        'sinopsi' => 'Las familias mafiosas de Nueva York entran en conflicto cuando el capo de una de las más poderosas, Vito Corleone y se lia',
        'durada' => '175 min',
        'director' => 'Francis Ford Coppola',
        'repartiment' => 'Marlon Brando, Al Pacino, James Caen',
        'qualificacio' => '+18',
        'genere' => 'Drama, Mafia, Crimen',
        'url_trailer' => 'https://www.youtube.com/watch?v=v72XprPxy3E',
    ]
];

?>