<?php
$peliculas = [
    [
        'nom' => 'El silencio de los corderos',
        'imatge' => 'https://static.filmin.es/images/es/media/26512/1/still_0_3_1920x1080.webp',
        'horaris_projeccio' => [
            '19:00',
            '21:30',
            '23:00',
        ],
        'sinopsi' => 'Una joven agente del FBI busca la ayuda de un prisionero, el Dr. Hannibal Lecter, un brillante psiquiatra y asesino en serie, para atrapar a otro asesino que ha secuestrado a una joven.',
        'durada' => '118 min',
        'director' => 'Jonathan Demme',
        'repartiment' => 'Jodie Foster, Anthony Hopkins, Scott Glenn',
        'qualificacio' => '+18',
        'genere' => 'Thriller, Terror, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/6iB21hsprAQ?si=1qm79vybDR55QVAS',
        'estrelles' => '4',
        'carrusel' => 'https://s2.ppllstatics.com/elcorreo/www/multimedia/202101/28/media/cortadas/Silencio-Anthony_Hopkins-k95B-U130354926801gOG-1248x770@RC.jpg',
        'carrusel2' => 'https://valenciaplaza.com/public/Image/2016/1/silenciodeloscorderos_NoticiaAmpliada.jpg',
        'carrusel3' => 'https://hips.hearstapps.com/hmg-prod/images/el-silencio-de-los-corderos-fotogramas-4-1611258199.jpg'
    ],
    [
        'nom' => 'Pulp Fiction',
        'imatge' => 'https://imagenes.elpais.com/resizer/v2/UU7EK3LSSRL77HQH5ZHQRJAJIA.jpg?auth=55427cda34ee0832111eb322a50b2305b17bcf0f8986aec80f41c7208a2aeeee&width=414',
        'horaris_projeccio' => [
            '20:00',
            '22:30',
            '21:00',
        ],
        'sinopsi' => 'Varias historias entrelazadas en el mundo del crimen de Los Ángeles, incluyendo a un boxeador, un asesino y una pareja de delincuentes.',
        'durada' => '154 min',
        'director' => 'Quentin Tarantino',
        'repartiment' => 'John Travolta, Uma Thurman, Samuel L. Jackson',
        'qualificacio' => '+18',
        'genere' => 'Acció, Drama, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/tGpTpVyI_OQ?si=A4ORZDNXpKvN5V3H',
        'estrelles' => '3',
        'carrusel' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2023/07/pulp-fiction-3089782.jpg?tf=3840x',
        'carrusel2' => 'https://estaticos-cdn.prensaiberica.es/clip/414ef4bf-a18f-42ea-8b34-0ccb1a891c0b_16-9-aspect-ratio_default_0.jpg',
        'carrusel3' => 'https://www.slashfilm.com/img/gallery/is-pulp-fiction-2-happening-what-quentin-tarantino-has-said-over-the-years/intro-1694555607.jpg'
    ],
    [
        'nom' => 'La lista de Schindler',
        'imatge' => 'https://www.autopista.es/uploads/s1/99/59/52/2/uno-de-los-carteles-de-la-aclamada-pelicula-la-lista-de-schindler.jpeg',
        'horaris_projeccio' => [
            '18:30',
            '19:30',
            '20:00',
        ],
        'sinopsi' => 'Oskar Schindler, un industrial alemán, arriesga la vida i la seva fortuna per salvar a més de mil jueus durant Holocaust.',
        'durada' => '195 min',
        'director' => 'Steven Spielberg',
        'repartiment' => 'Liam Neeson, Ben Kingsley, Ralph Fiennes',
        'qualificacio' => '+16',
        'genere' => 'Drama, Història',
        'url_trailer' => 'https://www.youtube.com/embed/7q-ETFeMxwI?si=Ujmijp6XKylEPcL8',
        'estrelles' => '1',
        'carrusel' => 'https://estaticosgn-cdn.deia.eus/clip/01b656ec-2873-494d-92bc-2dff8005b3fb_16-9-aspect-ratio_default_0.jpg',
        'carrusel2' => 'https://www.clarin.com/2016/02/05/HkemCefkVl_720x0.jpg',
        'carrusel3' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2017/06/schindler-s-list-original31.jpg?tf=3840x'
    ],
    [
        'nom' => 'Forrest Gump',
        'imatge' => 'https://cdn.aarp.net/content/dam/aarpe/es/home/entretenimiento/cine-y-television/info-2022/forrest-gump/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/entertainment/movies-for-grownups/2022/03/1140-forrest-gump-bench-esp.jpg',
        'horaris_projeccio' => [
            '20:00',
            '18:00',
            '21:15',
        ],
        'sinopsi' => 'La vida de Forrest Gump, un home amb discapacitat mental, que accidentalment influencia esdeveniments històrics a través de les dècades.',
        'durada' => '142 min',
        'director' => 'Robert Zemeckis',
        'repartiment' => 'Tom Hanks, Robin Wright, Gary Sinise',
        'qualificacio' => '+13',
        'genere' => 'Drama, Comèdia, Romance',
        'url_trailer' => 'https://www.youtube.com/embed/Cyh1LpxnaxI?si=OWY-VDhOBNmiyoba',
        'estrelles' => '5',
        'carrusel' => 'https://media.gq.com.mx/photos/5cb4b51f7a6d0e42a6c6e29a/16:9/w_2560%2Cc_limit/forrest.jpg',
        'carrusel2' => 'https://i.ytimg.com/vi/Cyh1LpxnaxI/maxresdefault.jpg',
        'carrusel3' => 'https://laopinion.com/wp-content/uploads/sites/3/2020/07/Forrest-Gump-running-ftr1.jpg?w=4096'
    ],
    [
        'nom' => 'Matrix',
        'imatge' => 'https://estaticos-cdn.prensaiberica.es/clip/3678c50c-e36a-4ce1-a8ea-bf7e6d655093_16-9-discover-aspect-ratio_default_0.jpg',
        'horaris_projeccio' => [
            '21:00',
            '19:15',
            '22:45',
        ],
        'sinopsi' => 'Thomas Anderson, un hacker conegut com a Neo, descobreix que el món és una simulació creada per màquines, i s uneix a una rebel·lia per alliberar la humanitat.',
        'durada' => '136 min',
        'director' => 'Lana Wachowski, Lilly Wachowski',
        'repartiment' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        'qualificacio' => '+16',
        'genere' => 'Acció, Ciència-Ficció',
        'url_trailer' => 'https://www.youtube.com/embed/vKQi3bBA1y8?si=qBgy_LvC-Y2vuaVK',
        'estrelles' => '4',
        'carrusel' => 'https://i.blogs.es/3bbc27/matrix1/1366_2000.jpg',
        'carrusel2' => 'https://phantom-elmundo.unidadeditorial.es/3b043128aa9ad1d1028455e58f612878/crop/0x83/1920x1363/resize/1200/f/webp/assets/multimedia/imagenes/2024/02/20/17084292985211.jpg',
        'carrusel3' => 'https://i.ytimg.com/vi/ECamB0bcQsY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAScDePFL2NYMUQVuJh46vz-aaV_g'
    ],
    [
        'nom' => 'Gladiator',
        'imatge' => 'https://fotografias.antena3.com/clipping/cmsimages01/2020/04/17/E8A1569F-D03B-41CE-99A1-0726EC2FF0BC/98.jpg?crop=1279,720,x0,y0&width=1900&height=1069&optimize=high&format=webply',
        'horaris_projeccio' => [
            '19:45',
            '20:15',
            '22:00',
        ],
        'sinopsi' => 'Un general romà és traït i venut com a esclau. Ara lluita per la seva vida com a gladiador i busca venjança contra qui el va traïr.',
        'durada' => '155 min',
        'director' => 'Ridley Scott',
        'repartiment' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
        'qualificacio' => '+16',
        'genere' => 'Acció, Drama, Història',
        'url_trailer' => 'https://www.youtube.com/embed/P5ieIbInFpg?si=av6elmRTBe329VQO',
        'estrelles' => '5',
        'carrusel' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2024/07/paul-mescal-gladiator-ii-3684825.jpg?tf=3840x',
        'carrusel2' => 'https://filasiete.com/wp-content/uploads/2024/04/gladiator2.jpg',
        'carrusel3' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2024/07/gladiator-ii-2024-3733672.jpg?tf=3840x'
    ],
    [
        'nom' => 'El gran Lebowski',
        'imatge' => 'https://pics.filmaffinity.com/El_gran_Lebowski-232559190-large.jpg',
        'horaris_projeccio' => [
            '21:30',
            '18:45',
            '20:30',
        ],
        'sinopsi' => 'Un hippie conegut com "El Dudo" es veu embolicat en una confusió que li porta a una sèrie de situacions còmiques i estranyes.',
        'durada' => '117 min',
        'director' => 'Joel Coen',
        'repartiment' => 'Jeff Bridges, John Goodman, Julianne Moore',
        'qualificacio' => '+18',
        'genere' => 'Comèdia, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/AkA69XT7Lq0?si=q0Ij96h8-hr_18yL',
        'estrelles' => '1',
        'carrusel' => 'https://hips.hearstapps.com/hmg-prod/images/el-gran-lebowski-bolera-1520464058.png',
        'carrusel2' => 'https://es.web.img3.acsta.net/r_1280_720/pictures/14/12/09/10/17/572032.jpg',
        'carrusel3' => 'https://crm.cinemateca.org.uy/media/films/screen_shot_2019-06-25_at_9.37.47_am.png'
    ],
    [
        'nom' => 'Inception',
        'imatge' => 'https://evoluciongeek.com/wp-content/uploads/2022/01/inception-01.jpg',
        'horaris_projeccio' => [
            '22:00',
            '20:45',
            '21:30',
        ],
        'sinopsi' => 'Un lladre especialitzat en robar idees a través dels somnis es veu obligat a realitzar l impossible: implantar una idea en la ment d una altra persona.',
        'durada' => '148 min',
        'director' => 'Christopher Nolan',
        'repartiment' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
        'qualificacio' => '+13',
        'genere' => 'Acció, Ciència-Ficció, Thriller',
        'url_trailer' => 'https://www.youtube.com/embed/YoHD9XEInc0?si=ue-fTGe7RdF7oA-H',
        'estrelles' => '3',
        'carrusel' => 'https://revistamutaciones.com/wp-content/uploads/2020/06/origen-inception-christopher-nolan-mutaciones-1.jpg',
        'carrusel2' => 'https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/peliculas/origen/galeria/3947111-4-esl-ES/Origen.jpg?crop=1xw:0.84375xh;center,top',
        'carrusel3' => 'https://www.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2014/06/346454-cine-ciencia-ficcion-critica-origen.jpg'
    ],
    [
        'nom' => 'El padrino',
        'imatge' => 'https://fotos.perfil.com/2021/03/14/trim/987/555/el-padrino-1144490.jpg',
        'horaris_projeccio' => [
            '18:00',
            '20:30',
            '22:00',
        ],
        'sinopsi' => 'Las familias mafiosas de Nueva York entran en conflicto cuando el capo de una de las más poderosas, Vito Corleone y se lia',
        'durada' => '175 min',
        'director' => 'Francis Ford Coppola',
        'repartiment' => 'Marlon Brando, Al Pacino, James Caen',
        'qualificacio' => '+18',
        'genere' => 'Drama, Mafia, Crimen',
        'url_trailer' => 'https://www.youtube.com/embed/v72XprPxy3E?si=-u1LXxsdS96Oo73S',
        'estrelles' => '5',
        'carrusel' => 'https://hyperbole.es/wp-content/uploads/2022/08/5OLYQAVEZBGMRLRWDIDUFBPUOI.jpg',
        'carrusel2' => 'https://media.revistagq.com/photos/5fc769f1be088082688e995b/16:9/w_2560%2Cc_limit/GettyImages-607408946.jpg',
        'carrusel3' => 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-131290713-1502182803.jpg?crop=1xw:1xh;center,top&resize=980:*'
    ]
];

?>